language: php

services:
  - docker

php:
  - 7.2

dist: trusty

sudo: required

before_install:
  - cp .env.travis .env
  - docker-compose build
  - docker-compose up -d
  - docker exec -it tasker-api.local composer install --no-interaction
  - docker exec -it tasker-api.local php artisan elastic:create-index App\\IndexConfigurator\\TaskIndexConfigurator
  - docker exec -it tasker-api.local php artisan migrate --seed


script:
  - vendor/bin/phpunit

notifications:
  email: false
