language: php

services:
  - mysql
php:
  - 7.1
  - hhvm

before_script:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE homestead_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit