language: php

services:
  - mysql

php:
  - 7.2

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

dist: trusty

sudo: required

before_script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan elastic:create-index App\\IndexConfigurator\\TaskIndexConfigurator
  - php artisan migrate --seed

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.1.deb && sudo dpkg -i --force-confnew elasticsearch-6.6.1.deb && sudo service elasticsearch restart
  - mysql -e 'CREATE DATABASE homestead;'

script:
  - vendor/bin/phpunit