language: php

services:
  - mysql
php:
  - 7.2

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

dist: trusty

sudo: required

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --seed

before_install:
  - mysql -e 'CREATE DATABASE homestead;'

script:
  - vendor/bin/phpunit