language: php

services:
  - mysql

php:
  - 7.2

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

dist: trusty

sudo: required


env:
  - ES_VERSION=6.5.0 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
  - sleep 15
  - sudo /usr/local/bin/elasticsearch-plugin install analysis-smartcn
  - sudo /usr/local/bin/elasticsearch -v

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan elastic:create-index App\\IndexConfigurator\\TaskIndexConfigurator
  - php artisan migrate --seed

before_install:
  - mysql -e 'CREATE DATABASE homestead;'

script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - vendor/bin/phpunit