language: php

services:
  - docker

php:
  - 7.2

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

dist: trusty

sudo: required

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan elastic:create-index App\\IndexConfigurator\\TaskIndexConfigurator
  - php artisan migrate --seed

before_install:
  - docker-compose build
  - docker-composer up -d
  - docker exec -it tasker-api.local php artisan elastic:create-index App\\IndexConfigurator\\TaskIndexConfigurator
  - docker exec -it tasker-api.local hp artisan migrate --seed


script:
  - vendor/bin/phpunit

notifications:
  email: false