version: '3'
services:
  web:
    build:
      context: ./docker
    container_name: tasker-api.local
    ports:
      - 8000:80
    links:
      - mysql
    volumes:
      - .:/var/www
      - ~/.ssh/:/root/.ssh/
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      DB_HOST: mysql
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 33061:3306
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    networks:
      - app-network

  elasticsearch:
    build:
      context: ./docker/elasticsearch
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
    ports:
      - 9200:9200
    networks:
      - app-network
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - app-network

volumes:
  mysqldata:
  redisdata:
  esdata:
networks:
  app-network:
    driver: "bridge"
