version: '3'
services:
  web:
    build:
      context: ./docker
    container_name: tasker-api.local
    ports:
      - "8000:80"
    links:
      - mysql
    volumes:
      - .:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini"
    environment:
      DB_HOST: mysql
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "33061:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    # https://github.com/docker/swarmkit/issues/1951
    ports:
      - "9200:9200"
    networks:
      - app-network
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - app-network

volumes:
  mysqldata:
  redisdata:
  elasticsearchdata:
networks:
  app-network:
    driver: "bridge"